In [1]:
import pandas as ps
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC,SVR       

In [2]:
df =ps.read_csv('clean_loan_data.csv')

In [3]:
df.drop(["Unnamed: 0",	"name"], axis = 1 , inplace = True)

In [4]:
x =df.drop("loan_approved", axis=1)

In [5]:
y =df[['loan_approved']]

In [6]:
y['loan_approved'].value_counts() 

loan_approved
1    1121
2     879
Name: count, dtype: int64

In [7]:
x_train, x_test,  y_train , y_test =train_test_split(x , y ,test_size=0.2, random_state=42)
x_train.shape, y_train.shape , x_test.shape, y_test.shape

((1600, 4), (1600, 1), (400, 4), (400, 1))

In [8]:
from sklearn.svm import SVC,SVR
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dtc=DecisionTreeClassifier(criterion='entropy')
dtc.fit(x_train, y_train)
y_pred =dtc.predict(x_test)
dtc.predict([[130290,	447,	16496,	10]])
print(dtc.score(x_train, y_train))
print(dtc.score(x_test, y_test))
dtc.get_params()


1.0
0.9675


c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

| Topic                   | Real-World Example                                                                |
| ----------------------- | --------------------------------------------------------------------------------- |
| **Decorators**          | In a FastAPI application, decorators like `@app.get("/users")` define API routes. |
| **Generators**          | Reading a 10GB log file line by line without loading the entire file into memory. |
| **Iterators**           | Processing records from a database one at a time.                                 |
| **Lambda Functions**    | Sorting products by price in an e-commerce website.                               |
| **List Comprehensions** | Creating a list of cleaned customer names from raw data.                          |
| **Multithreading**      | Downloading multiple files simultaneously.                                        |
| **Multiprocessing**     | Training Machine Learning models using multiple CPU cores.                        |
| **Asyncio**             | Handling thousands of API requests in a chatbot or web server.                    |
| **Context Managers**    | Automatically closing database connections and files.                             |
| **Exception Handling**  | Preventing an application from crashing when an API is unavailable.               |
| **Type Hinting**        | Making large enterprise codebases easier to maintain.                             |
| **Design Patterns**     | Building scalable software architectures.                                         |


### Model Evaluation Techniques
* Model Evaluation Techniques are used to measure how well a Machine Learning model performs on unseen data.

| Actual/Predicted | Positive | Negative |
| ---------------- | -------- | -------- |
| Positive         | TP       | FN       |
| Negative         | FP       | TN       |


In [9]:
from sklearn.metrics import  confusion_matrix
confusion_matrix(y_test, y_pred) 

array([[211,   6],
       [  7, 176]], dtype=int64)

| AUC Score  | Performance       |
| ---------- | ----------------- |
| 1.0        | Perfect Model     |
| 0.9 - 0.99 | Excellent         |
| 0.8 - 0.89 | Good              |
| 0.7 - 0.79 | Fair              |
| 0.5        | Random Guessing   |
| < 0.5      | Worse than Random |


In [10]:
### Classification Evaluation Metrics
# A. Accuracy
# Measures the percentage of correct predictions.

# Accuracy=Correct Predictions​/Total Predictions

# Example:

# Total samples = 100
# Correct predictions = 90

# Accuracy = 90%



# B. Precision  
# Out of all predicted positives, how many are actually positive.

# Tp/TP+FP

# Tp/TP+FN>>>>>>recalll   >>  Out of all actual positives, how many were correctly identified.



### fi -score   Balance between Precision and Recall.   >>>>  2 × (Precision × Recall) / (Precision + Recall)


| Metric               | Description                                                      |
| -------------------- | ---------------------------------------------------------------- |
| **Accuracy**         | Percentage of correct predictions.                               |
| **Precision**        | Out of all predicted positives, how many are actually positive.  |
| **Recall**           | Out of all actual positives, how many were correctly identified. |
| **F1-Score**         | Balance between Precision and Recall.                            |
| **ROC-AUC**          | Measures the model's ability to distinguish between classes.     |
| **Confusion Matrix** | Shows TP, TN, FP, and FN predictions.                            |


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.97      0.97      0.97       217
           2       0.97      0.96      0.96       183

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400



In [13]:
# mse
from sklearn.metrics import mean_squared_error as mse 
mse(y_test, y_pred) 

0.0325

In [14]:
from sklearn.datasets import  fetch_california_housing

In [15]:
x , y =fetch_california_housing(return_X_y=True)

In [16]:
x 

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [17]:
y 

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [18]:
x_train, x_test,  y_train , y_test =train_test_split(x , y ,test_size=0.2, random_state=42)
x_train.shape, y_train.shape , x_test.shape, y_test.shape

((16512, 8), (16512,), (4128, 8), (4128,))

In [19]:
from sklearn.tree import DecisionTreeRegressor
dtr =DecisionTreeRegressor()
dtr.fit(x_train, y_train)

,criterion,'squared_error'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,ccp_alpha,0.0


In [20]:
dtr.score(x_train, y_train)

1.0

In [21]:
dtr.score(x_test, y_test)

0.6300856931767544

In [22]:
y_pred =dtr.predict(x_test)

In [23]:
y_pred

array([0.425  , 1.203  , 5.00001, ..., 5.00001, 0.656  , 2.172  ])

In [26]:
import numpy as np 
np.sqrt(25)

5.0

In [24]:
# mse mae 
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("mean_squared_error:- ",mean_squared_error(y_test, y_pred))
print("mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

mean_squared_error:-  0.4847390288409399
mean_absolute_error:- 0.452834917635659


In [27]:
rmse =np.sqrt(mean_squared_error(y_test, y_pred))

In [28]:
rmse

0.6962320222748591

In [14]:
from sklearn.datasets import load_breast_cancer
x , y = load_breast_cancer(return_X_y=True)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test,  y_train , y_test =train_test_split(x , y ,test_size=0.2, random_state=42)
x_train.shape, y_train.shape , x_test.shape, y_test.shape
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [17]:
pred =knn.predict(x_test)

In [18]:
pred 

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [19]:
y_test 

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [20]:
knn.score(x_test, y_test )

0.956140350877193

In [21]:
knn.score(x_train, y_train)

0.9406593406593406

In [ ]:
# without hyper parameter 
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier()
rfc.get_params()

In [24]:
rfc.fit(x_train, y_train )

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [25]:
print(rfc.score(x_test, y_test ))
print(rfc.score(x_train,y_train))



0.956140350877193
1.0


In [ ]:
# with hyper parameter 
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier(n_estimators=150, criterion='entropy', max_depth=1, min_samples_split=2)
rfc.fit(x_train, y_train )
print(rfc.score(x_test, y_test ))
print(rfc.score(x_train,y_train))

0.956140350877193
0.9296703296703297


In [27]:
rfc.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 1,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 150,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}