In [1]:
! pip install numpy

In [2]:
# pip install numpy
print("hello hii kese ho ")

hello hii kese ho 


In [3]:
# python -m venv 
# venv/Scripts/activate
# deactivate
import numpy as np 

In [4]:
np.__version__

'2.4.6'

In [5]:
lst =list(range(1,20))

In [6]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [7]:
type(lst)

list

In [8]:
arr =np.array(lst)

In [9]:
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
lst = [1,2,5,2,5,5]
arr =np.array(lst)

In [11]:
type(arr) 


numpy.ndarray

In [12]:
arr =np.array([1,2,5,2,58,2,8,2,5,522,5,2,5,2,5,2,5,5])

In [13]:
arr =np.array([range(1,20)])

In [14]:
type(arr )

numpy.ndarray

In [15]:
arr =np.arange(1,21)

In [16]:
type(arr )

numpy.ndarray

In [17]:
arr =np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arr 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr =np.ones(10)

In [20]:
arr 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
arr =np.zeros((5,10)) 
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr =np.zeros((5,10)) 
print(arr.ndim)

2


In [23]:
arr =np.linspace(1,10,5)
print(arr)
print(type(arr ))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [24]:
arr =np.arange(0,30)

In [25]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
# np.reshape()
arr =arr.reshape(10,3)

In [27]:
arr 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [28]:
arr =arr.reshape(5,6)


In [29]:
arr 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
arr =arr.reshape(6,5)


In [31]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [32]:
arr = np.random.randint(1,5,10)
arr 

array([1, 2, 3, 3, 3, 2, 1, 4, 3, 2], dtype=int32)

In [33]:
arr = np.random.randint(1,5,(5,6))
arr 

array([[2, 4, 2, 4, 2, 4],
       [2, 2, 1, 2, 2, 2],
       [3, 2, 4, 4, 4, 4],
       [3, 2, 2, 4, 1, 1],
       [4, 3, 3, 1, 3, 2]], dtype=int32)

In [34]:
arr =np.random.random(10)
arr 

array([0.04795016, 0.41466047, 0.64926887, 0.25031955, 0.75419404,
       0.89114287, 0.72340461, 0.85435067, 0.83760475, 0.33722321])

In [35]:
arr =np.random.random((10, 3))
arr 

array([[0.32833079, 0.54826064, 0.5979854 ],
       [0.17299598, 0.38607815, 0.49747871],
       [0.66299763, 0.24587645, 0.41484438],
       [0.4647033 , 0.52855726, 0.89137478],
       [0.88046807, 0.88242621, 0.82025699],
       [0.6130863 , 0.62575903, 0.8856748 ],
       [0.11842942, 0.126257  , 0.39128105],
       [0.91185012, 0.7141256 , 0.68301091],
       [0.30667052, 0.38181219, 0.29230385],
       [0.98174855, 0.1809039 , 0.22467998]])

In [36]:
arr =np.arange(60).reshape(12,5)
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [37]:
print("number of dim :- ",arr.ndim)
print("shape of array :- ",arr.shape)
print("data types of item:- ",arr.dtype)
print("size of array :- ",arr.size)

number of dim :-  2
shape of array :-  (12, 5)
data types of item:-  int64
size of array :-  60


In [38]:
lst = [[1,2,3],[4,5,6]]
lst 

[[1, 2, 3], [4, 5, 6]]

In [39]:
arr =np.array(lst)

In [40]:
arr 

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr =np.arange(60).reshape(12,5)

In [42]:
arr.shape

(12, 5)

In [43]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [44]:
# arr.transpose

In [45]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [46]:
# arr[0,0]     0 row , coloum 

In [47]:
# arr[0][0]

In [48]:
arr[11,4]

np.int64(59)

In [49]:
arr[-1,-1]

np.int64(59)

In [50]:
arr[11,-1]

np.int64(59)

In [51]:
arr[-1,4]

np.int64(59)

In [52]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [53]:
arr[0:9,3:4]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28],
       [33],
       [38],
       [43]])

In [54]:
arr[2:4,3:]

array([[13, 14],
       [18, 19]])

In [55]:
arr[9:11,1:3]

array([[46, 47],
       [51, 52]])

In [56]:
arr[5:7,2:4]

array([[27, 28],
       [32, 33]])

In [57]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [58]:
arr[-1,-1]=100

In [59]:
arr 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [60]:
print("number of dim :- ",arr.ndim)
print("shape of array :- ",arr.shape)
print("data types of item:- ",arr.dtype)
print("size of array :- ",arr.size)

number of dim :-  2
shape of array :-  (12, 5)
data types of item:-  int64
size of array :-  60


In [61]:
arr =np.arange(225).reshape(5,15,3)

In [62]:
arr 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [65]:
arr[0][0][0]

np.int64(0)

In [66]:
arr[-1]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [67]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [70]:
arr[0,0,0]

np.int64(0)

In [72]:
arr[0:5,0]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [73]:
arr[0,0,0]

np.int64(0)

In [75]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [76]:
print("number of dim :- ",arr.ndim)
print("shape of array :- ",arr.shape)
print("data types of item:- ",arr.dtype)
print("size of array :- ",arr.size)

number of dim :-  3
shape of array :-  (5, 15, 3)
data types of item:-  int64
size of array :-  225


In [78]:
arr1 = np.array([1,2,89,2,8,2,8])
arr2 =np.array([8,5,2,6,25,2,52])
print(arr1*arr2)
print(arr1/arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*+arr2)
print(arr1//+arr2)



[  8  10 178  12 200   4 416]
[ 0.125       0.4        44.5         0.33333333  0.32        1.
  0.15384615]
[ 9  7 91  8 33  4 60]
[ -7  -3  87  -4 -17   0 -44]
[  8  10 178  12 200   4 416]
[ 0  0 44  0  0  1  0]


In [77]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)


Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]


In [80]:
arr1.sort()


In [81]:
arr =np.arange(225)

In [82]:
arr 

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [83]:
arr =arr.reshape(5,15,3)

In [84]:
arr 

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11